### ISSUE TITLE
files set to read only

### ISSUE THREAD

**Issue by geddski** [maxogden/extract-zip#12]
When I extract a zip, the folder gets read/write but the files inside it get read only permissions. Is there a way to set them all to read/write?

**Comment by maxogden** [comment]
Here's the code https://github.com/maxogden/extract-zip/blob/6713c075ca5e4609f0e8a3f0627e5b5a2074c796/index.js#L68-L72

I'm guessing it's happening because your zip doesn't include a mode to use. There isn't currently a way to override the default but I'd be happy to accept a patch adding a defaultFilePermission option.

It might also make sense to just default to read/write rather than just readable, I just picked readable because it seemed like a sensible default at the time for files without an explicit mode set.

**Comment by geddski** [comment]
thx for the reply. As a quick workaround I reset the permissions recursively using shelljs:

```js
shell.chmod('-R', 'u+w', target);
```

I like your idea of changing the default to read/write, as that's the default permissions (at least on OSX) when you create a file yourself.
